MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/ruichen/Documents/Documents_from_ubuntu_1604/shanghai_store/model_save/model_0200000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256)
    ANCHOR_STRIDE: (4, 8, 16, 32)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 31  # num skus classes + background
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 400
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True    
DATASETS:
  TRAIN: ("shanghai_store_train_unannotated", )
  TEST: ("shanghai_store_test_size_512_centered", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 210000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 5000
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "/home/ruichen/Documents/Documents_from_ubuntu_1604/shanghai_store/model_save"
