MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 31
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 400
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True
DATASETS:
  TRAIN: ("visual_pr_30skus_cam100_9k_imgs", "visual_pr_30skus_cam29_13k_imgs", "visual_pr_30skus_cam30_13k_imgs", "visual_pr_30skus_cam31_13k_imgs", "visual_pr_30skus_shelf_dark_4k_imgs", "visual_pr_30skus_shelf_light_2k_imgs_cam1", "visual_pr_30skus_shelf_light_2k_imgs_cam2", "visual_pr_30skus_green_screen_data_v4")
  TEST: ("test_visual_pr_30skus_cam29_batch2_imgs", "test_visual_pr_30skus_cam30_batch2_imgs")
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 250000
  IMS_PER_BATCH: 12
  CHECKPOINT_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 3
