MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/rui/photobox2real/model_before_adapt/model_0050000.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.333, 0.5, 0.8, 1, 1.25, 2.0, 3.0)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 201  # num skus classes + background
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 400
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True    
DATASETS:
  TRAIN: ("sku_box_online",)
  TEST: ("sku-box-full-test-pilot1-photobox",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (150000, 200000, 300000)
  MAX_ITER: 400000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 1  
OUTPUT_DIR: "/home/rui/photobox2real/model_before_adapt"

